/**
 * Lista curada de presentes comuns e divertidos para lista de casamento.
 * Imagens servidas diretamente de /gifts/ no servidor.
 * Sites deixados em branco para o casal preencher depois.
 */
export const DEFAULT_GIFTS = [
  // --- COTAS DE SOBREVIVÊNCIA ---
  {
    id: 'tpm',
    nome: '<<Descreva o que você quer receber em forma de dinheiro>>',
    preco: 100,
    imagem_url: '/gifts/dinheiroparacasal.webp',
    categoria: 'Sobrevivência',
    emoji: '🍫',
    descricao: 'Para quem desejar nos presentear, optamos por receber uma contribuição em dinheiro, que será utilizada para realizar nossos sonhos e construir nossa nova vida juntos.',
    sites: [],
  },
  {
    id: 'tpm',
    nome: 'Fundo de Emergência para TPM',
    preco: 50,
    imagem_url: '/gifts/tpm.svg',
    categoria: 'Sobrevivência',
    emoji: '🍫',
    descricao: 'Para garantir que o estoque de chocolate nunca acabe e a paz reine no lar nos dias difíceis.',
    sites: [],
  },
  {
    id: 'massagem',
    nome: 'Massagem Relaxante Pós-Fatura',
    preco: 100,
    imagem_url: '/gifts/aspirador.svg',
    categoria: 'Sobrevivência',
    emoji: '💆',
    descricao: 'Um carinho especial para o noivo não desmaiar quando a fatura do cartão com os custos da festa chegar.',
    sites: [],
  },
  {
    id: 'almofada_paz',
    nome: 'Almofada Zona de Paz',
    preco: 60,
    imagem_url: '/gifts/jogo_cama.svg',
    categoria: 'Sobrevivência',
    emoji: '🧘',
    descricao: 'O acessório indispensável para os momentos de discussão: quem segurar a almofada tem o direito de falar (ou de pedir desculpas).',
    sites: [],
  },
  {
    id: 'vaquinha',
    nome: 'Vaquinha para Noivos Quebrados',
    preco: 200,
    imagem_url: '/gifts/vaquinha.svg',
    categoria: 'Sobrevivência',
    emoji: '🐮',
    descricao: 'Ajudinha sincera para quem gastou tudo no buffet e agora precisa de dinheiro para o pão de cada dia.',
    sites: [],
  },
  {
    id: 'lencol_elastico',
    nome: 'Curso: Como Dobrar Lençol de Elástico',
    preco: 30,
    imagem_url: '/gifts/edredom.svg',
    categoria: 'Sobrevivência',
    emoji: '📐',
    descricao: 'Investimento educacional para evitar que o armário de roupas pareça um ninho de mafagafos.',
    sites: [],
  },

  // --- LUA DE MEL DIVERTIDA ---
  {
    id: 'cafe_aeroporto',
    nome: 'Cafezinho Superfaturado no Aeroporto',
    preco: 25,
    imagem_url: '/gifts/cafeteira.webp',
    categoria: 'Lua de Mel',
    emoji: '☕',
    descricao: 'Pague esse café para a gente não ter que vender um rim logo na primeira conexão da viagem.',
    sites: [],
  },
  {
    id: 'pao_alho',
    nome: 'Pão de Alho à Vontade',
    preco: 40,
    imagem_url: '/gifts/churrasco.svg',
    categoria: 'Lua de Mel',
    emoji: '🥖',
    descricao: 'Para garantir que o hálito de alho seja a única preocupação do casal durante o churrasco da viagem.',
    sites: [],
  },
  {
    id: 'carinho_animal',
    nome: 'Taxa para Carinho em Animal Local',
    preco: 80,
    imagem_url: '/gifts/viagem.svg',
    categoria: 'Lua de Mel',
    emoji: '🦜',
    descricao: 'Cota destinada a alimentar a obsessão da noiva (ou do noivo) por tentar ser amigo de todo bicho que encontrar.',
    sites: [],
  },
  {
    id: 'insolacao',
    nome: 'Proteção Contra Insolação',
    preco: 45,
    imagem_url: '/gifts/viagem.svg',
    categoria: 'Lua de Mel',
    emoji: '☀️',
    descricao: 'Para não voltarmos da lua de mel parecendo dois pimentões cozidos.',
    sites: [],
  },
  {
    id: 'mico_pista',
    nome: 'Mico na Pista de Dança',
    preco: 150,
    imagem_url: '/gifts/viagem.svg',
    categoria: 'Lua de Mel',
    emoji: '💃',
    descricao: 'Um vale para a gente passar vergonha na pista sem se preocupar com o amanhã. O que acontece na lua de mel, fica na lua de mel!',
    sites: [],
  },

  // --- UTENSÍLIOS SINCEROS ---
  {
    id: 'avental_ajudante',
    nome: 'Avental "Ajudante por Obrigação"',
    preco: 35,
    imagem_url: '/gifts/panelas.webp',
    categoria: 'Utensílios',
    emoji: '👨‍🍳',
    descricao: 'Uniforme oficial para quem só vai para a cozinha para lavar a louça ou perguntar "já tá pronto?".',
    sites: [],
  },
  {
    id: 'caneca_dr',
    nome: 'Caneca "Primeiro Café, Depois DR"',
    preco: 28,
    imagem_url: '/gifts/cafeteira.webp',
    categoria: 'Utensílios',
    emoji: '🥛',
    descricao: 'Aviso de segurança essencial para as manhãs: discussões de relacionamento apenas após a cafeína fazer efeito.',
    sites: [],
  },
  {
    id: 'lanche_madrugada',
    nome: 'Sanduicheira pro Lanchinho da Madrugada',
    preco: 90,
    imagem_url: '/gifts/airfryer.webp',
    categoria: 'Utensílios',
    emoji: '🥪',
    descricao: 'A salvadora oficial das laricas pós-balada ou das maratonas de séries até as 3 da manhã.',
    sites: [],
  },
  {
    id: 'tabua_churrasco',
    nome: 'Tábua "Aqui Só Entra Churrasco Aprovado"',
    preco: 75,
    imagem_url: '/gifts/churrasco.svg',
    categoria: 'Utensílios',
    emoji: '🥩',
    descricao: 'Para dar autoridade ao churrasqueiro oficial da casa (mesmo que ele queime a carne de vez em quando).',
    sites: [],
  },
  {
    id: 'lencos_mae',
    nome: 'Lenços para a Mãe da Noiva',
    preco: 20,
    imagem_url: '/gifts/toalhas.webp',
    categoria: 'Utensílios',
    emoji: '🤧',
    descricao: 'Kit de contenção de lágrimas para a cerimônia. Avisamos: vai precisar de mais de um!',
    sites: [],
  },

  // --- COZINHA ---
  {
    id: 'panelas',
    nome: 'Jogo de Panelas Antiaderentes',
    preco: 350,
    imagem_url: '/gifts/panelas.webp',
    categoria: 'Cozinha',
    emoji: '🍳',
    descricao: 'Um clássico que não pode faltar. Porque cozinhar é bom, mas lavar panela grudada ninguém merece.',
    sites: [],
  },
  {
    id: 'batedeira',
    nome: 'Batedeira Planetária',
    preco: 650,
    imagem_url: '/gifts/batedeira.webp',
    categoria: 'Cozinha',
    emoji: '🥣',
    descricao: 'Para os noivos que sonham em ser MasterChef ou só querem fazer um bolo de caneca com estilo.',
    sites: [],
  },
  {
    id: 'airfryer',
    nome: 'Air Fryer Digital',
    preco: 320,
    imagem_url: '/gifts/airfryer.webp',
    categoria: 'Cozinha',
    emoji: '🍟',
    descricao: 'O eletrodoméstico que mudou a vida moderna. Batata frita sem óleo e sem culpa (ou quase isso).',
    sites: [],
  },
  {
    id: 'cafeteira',
    nome: 'Cafeteira Elétrica',
    preco: 220,
    imagem_url: '/gifts/cafeteira.webp',
    categoria: 'Cozinha',
    emoji: '☕',
    descricao: 'Café fresquinho a qualquer hora para manter os noivos acordados durante o planejamento do casamento.',
    sites: [],
  },
  {
    id: 'liquidificador',
    nome: 'Liquidificador Turbo',
    preco: 180,
    imagem_url: '/gifts/liquidificador.svg',
    categoria: 'Cozinha',
    emoji: '🥤',
    descricao: 'Para sucos, vitaminas e aquela marguerita especial no fim de semana.',
    sites: [],
  },
  {
    id: 'microondas',
    nome: 'Micro-ondas 30L',
    preco: 550,
    imagem_url: '/gifts/microondas.svg',
    categoria: 'Cozinha',
    emoji: '🍿',
    descricao: 'Praticidade total para esquentar a janta ou fazer aquela pipoca de cinema.',
    sites: [],
  },

  // --- QUARTO & BANHEIRO ---
  {
    id: 'toalhas',
    nome: 'Jogo de Toalhas de Banho',
    preco: 160,
    imagem_url: '/gifts/toalhas.webp',
    categoria: 'Banheiro',
    emoji: '🪥',
    descricao: 'Toalhas fofinhas para transformar o banho pós-trabalho em um momento de spa.',
    sites: [],
  },
  {
    id: 'jogo_cama',
    nome: 'Jogo de Cama Algodão 200 Fios',
    preco: 280,
    imagem_url: '/gifts/jogo_cama.svg',
    categoria: 'Quarto',
    emoji: '🛏️',
    descricao: 'Conforto e elegância para as noites de sono do novo casal.',
    sites: [],
  },
  {
    id: 'edredom',
    nome: 'Edredom King Size',
    preco: 450,
    imagem_url: '/gifts/edredom.svg',
    categoria: 'Quarto',
    emoji: '☁️',
    descricao: 'Parece que você está dormindo em uma nuvem. Essencial para os dias de frio.',
    sites: [],
  },

  // --- CASA & MESA ---
  {
    id: 'aspirador',
    nome: 'Robô Aspirador de Pó',
    preco: 850,
    imagem_url: '/gifts/aspirador.svg',
    categoria: 'Casa',
    emoji: '🤖',
    descricao: 'O melhor amigo do casal: limpa a casa sozinho enquanto vocês aproveitam o tempo juntos.',
    sites: [],
  },
  {
    id: 'talheres',
    nome: 'Jogo de Talheres 42 peças',
    preco: 190,
    imagem_url: '/gifts/talheres.svg',
    categoria: 'Mesa',
    emoji: '🍴',
    descricao: 'Talheres elegantes para receber a família e os amigos com todo o requinte.',
    sites: [],
  },
  {
    id: 'jantar',
    nome: 'Aparelho de Jantar 20 peças',
    preco: 420,
    imagem_url: '/gifts/pratos.svg',
    categoria: 'Mesa',
    emoji: '🍽️',
    descricao: 'Pratos lindos para servir as primeiras refeições na casa nova.',
    sites: [],
  },

  // --- LISTA DIVERTIDA ---
  {
    id: 'ajude_lua_mel',
    nome: 'Ajudar a pagar a lua de mel',
    preco: 531.86,
    imagem_url: '/gifts/funny/ajude-a-pagar-a-lua-mel-do-casal.webp',
    categoria: 'Lista Divertida',
    emoji: '🌴',
    descricao: 'Uma contribuição para transformar a lua de mel em uma lembrança inesquecível — e com menos estresse financeiro.',
    sites: [],
  },
  {
    id: 'primeiro_lugar_buffet',
    nome: 'Primeiro lugar na fila do buffet',
    preco: 531.86,
    imagem_url: '/gifts/funny/primeiro-lugar-na-fila-do-buffet.webp',
    categoria: 'Lista Divertida',
    emoji: '🍽️',
    descricao: 'Porque o melhor lugar para comer é sempre o primeiro da fila — e o mais digno de um bom brinde.',
    sites: [],
  },
  {
    id: 'relogio_noiva',
    nome: 'Relógio para a noiva não se atrasar',
    preco: 372.3,
    imagem_url: '/gifts/funny/relogio-para-a-noiva-nao-se-atrasar.webp',
    categoria: 'Lista Divertida',
    emoji: '⏰',
    descricao: 'Um presente certeiro para manter a noiva no horário e a festa em paz.',
    sites: [],
  },
  {
    id: 'dancinha_tiktok',
    nome: 'Dancinha do TikTok com o casal',
    preco: 276.57,
    imagem_url: '/gifts/funny/Dancinha%20do%20TikTok%20com%20o%20casal.webp',
    categoria: 'Lista Divertida',
    emoji: '🕺',
    descricao: 'Para registrar o momento mais espontâneo e memorável da noite — com direito a coreografia.',
    sites: [],
  },
  {
    id: 'calmantes_casamento',
    nome: 'Calmantes para o dia do casamento',
    preco: 159.56,
    imagem_url: '/gifts/funny/Calmantes%20para%20o%20dia%20do%20casamento.webp',
    categoria: 'Lista Divertida',
    emoji: '💊',
    descricao: 'A contribuição perfeita para manter a serenidade no momento em que tudo precisa acontecer no tempo certo.',
    sites: [],
  },
  {
    id: 'jogo_panelas_moderno',
    nome: 'Jogo de panelas moderno',
    preco: 212.74,
    imagem_url: '/gifts/funny/Jogo%20de%20panelas%20moderno.webp',
    categoria: 'Lista Divertida',
    emoji: '🍳',
    descricao: 'Para quem prefere cozinhar com estilo e garantir que o molho não grude na panela de sempre.',
    sites: [],
  },
  {
    id: 'taxa_filhos',
    nome: 'Taxa para perguntar quando o casal vai ter filhos',
    preco: 212.74,
    imagem_url: '/gifts/funny/taxa-para-perguntar-quando-o-casal-vai-ter-filhos.webp',
    categoria: 'Lista Divertida',
    emoji: '👶',
    descricao: 'A pergunta mais delicada da família merece um valor simbólico e muito humor.',
    sites: [],
  },
  {
    id: 'jogar_buque',
    nome: 'Jogar o buquê na sua direção',
    preco: 159.56,
    imagem_url: '/gifts/funny/Jogar%20o%20buquê%20na%20sua%20direção.webp',
    categoria: 'Lista Divertida',
    emoji: '💐',
    descricao: 'Uma proposta ousada para quem quer transformar a tradição em um momento ainda mais memorável.',
    sites: [],
  },
  {
    id: 'taxa_nao_jogar_buque',
    nome: 'Taxa para não jogar o buquê na sua direção',
    preco: 212.74,
    imagem_url: '/gifts/funny/Taxa%20para%20N%C3%83O%20jogar%20o%20buquê%20na%20sua%20direção.webp',
    categoria: 'Lista Divertida',
    emoji: '🚫',
    descricao: 'Uma forma bastante eficiente de proteger a festa e manter a tradição em segurança.',
    sites: [],
  },
  {
    id: 'faqueiro_raiz',
    nome: 'Faqueiro para cortar o problema pela raiz',
    preco: 159.56,
    imagem_url: '/gifts/funny/Faqueiro%20para%20cortar%20o%20problema%20pela%20raiz.webp',
    categoria: 'Lista Divertida',
    emoji: '🔪',
    descricao: 'Para quem acredita que o melhor jeito de resolver qualquer drama é com humor e uma boa ferramenta.',
    sites: [],
  },
  {
    id: 'dar_pitaco',
    nome: 'Dar pitaco ou falar mal da festa',
    preco: 1107.22,
    imagem_url: '/gifts/funny/Dar%20pitaco%20ou%20falar%20mal%20da%20festa.webp',
    categoria: 'Lista Divertida',
    emoji: '🗣️',
    descricao: 'A contribuição oficial para quem sempre acha que tem uma opinião tão boa quanto a da noiva e do noivo.',
    sites: [],
  },
  {
    id: 'ajude_aluguel',
    nome: 'Contribuição para a casa nova',
    preco: 850.97,
    imagem_url: '/gifts/funny/Ajude%20a%20pagar%20o%20aluguel.webp',
    categoria: 'Lista Divertida',
    emoji: '🏠',
    descricao: 'Uma ajuda bem-humorada para deixar a casa nova mais confortável e o planejamento menos apertado.',
    sites: [],
  },
  {
    id: 'taxa_ir_de_branco',
    nome: 'Taxa para ir de branco com toda a cara de pau',
    preco: 10680.25,
    imagem_url: '/gifts/funny/Taxa%20para%20ter%20a%20cara%20de%20pau%20de%20ir%20de%20branco.webp',
    categoria: 'Lista Divertida',
    emoji: '🤍',
    descricao: 'O presente mais ousado da lista: para quem não liga para tradição e quer entrar na festa com estilo.',
    sites: [],
  },
];

export const CATEGORIAS = [...new Set(DEFAULT_GIFTS.map(g => g.categoria))];
