/**
 * Lista curada de presentes comuns para lista de casamento.
 * Imagens servidas diretamente de /gifts/ no servidor.
 * Sites deixados em branco para o casal preencher depois.
 */
export const DEFAULT_GIFTS = [
  {
    id: 'panelas',
    nome: 'Jogo de Panelas Antiaderentes',
    preco: 350,
    imagem_url: '/gifts/panelas.png',
    categoria: 'Cozinha',
    emoji: '🍳',
    sites: [],
  },
  {
    id: 'batedeira',
    nome: 'Batedeira Planetária',
    preco: 650,
    imagem_url: '/gifts/batedeira.png',
    categoria: 'Cozinha',
    emoji: '🥣',
    sites: [],
  },
  {
    id: 'airfryer',
    nome: 'Air Fryer Digital',
    preco: 320,
    imagem_url: '/gifts/airfryer.png',
    categoria: 'Cozinha',
    emoji: '🍟',
    sites: [],
  },
  {
    id: 'cafeteira',
    nome: 'Cafeteira Elétrica',
    preco: 220,
    imagem_url: '/gifts/cafeteira.png',
    categoria: 'Cozinha',
    emoji: '☕',
    sites: [],
  },
  {
    id: 'liquidificador',
    nome: 'Liquidificador Potente',
    preco: 180,
    imagem_url: '/gifts/liquidificador.svg',
    categoria: 'Cozinha',
    emoji: '🥤',
    sites: [],
  },
  {
    id: 'microondas',
    nome: 'Micro-ondas',
    preco: 420,
    imagem_url: '/gifts/microondas.svg',
    categoria: 'Cozinha',
    emoji: '📡',
    sites: [],
  },
  {
    id: 'jogo_cama',
    nome: 'Jogo de Cama Casal',
    preco: 280,
    imagem_url: '/gifts/jogo_cama.svg',
    categoria: 'Quarto',
    emoji: '🛏️',
    sites: [],
  },
  {
    id: 'edredom',
    nome: 'Edredom Casal',
    preco: 250,
    imagem_url: '/gifts/edredom.svg',
    categoria: 'Quarto',
    emoji: '🛌',
    sites: [],
  },
  {
    id: 'toalhas',
    nome: 'Jogo de Toalhas de Banho',
    preco: 160,
    imagem_url: '/gifts/toalhas.png',
    categoria: 'Banheiro',
    emoji: '🪥',
    sites: [],
  },
  {
    id: 'talheres',
    nome: 'Jogo de Talheres (24 peças)',
    preco: 190,
    imagem_url: '/gifts/talheres.svg',
    categoria: 'Mesa',
    emoji: '🍴',
    sites: [],
  },
  {
    id: 'pratos',
    nome: 'Aparelho de Jantar',
    preco: 300,
    imagem_url: '/gifts/pratos.svg',
    categoria: 'Mesa',
    emoji: '🍽️',
    sites: [],
  },
  {
    id: 'aspirador',
    nome: 'Robô Aspirador',
    preco: 800,
    imagem_url: '/gifts/aspirador.svg',
    categoria: 'Casa',
    emoji: '🤖',
    sites: [],
  },
];

export const CATEGORIAS = [...new Set(DEFAULT_GIFTS.map(g => g.categoria))];
